# Generated by Django 5.2.4 on 2025-08-10 00:34

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="primary_cv",
            field=models.FileField(
                blank=True,
                help_text="Primary CV file",
                null=True,
                upload_to=accounts.models.get_cv_upload_path,
            ),
        ),
    ]
