# Generated by Django 5.2.4 on 2025-08-10 00:34

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                help_text="Company banner/cover image",
                null=True,
                upload_to=companies.models.get_company_banner_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Company logo image",
                null=True,
                upload_to=companies.models.get_company_logo_upload_path,
            ),
        ),
    ]
