# Generated by Django 5.2.4 on 2025-08-05 23:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title/position name', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly job identifier', max_length=255, unique=True)),
                ('description', models.TextField(help_text='Full job description and requirements')),
                ('responsibilities', models.TextField(blank=True, help_text='Key responsibilities and duties')),
                ('requirements', models.TextField(blank=True, help_text='Required qualifications and skills')),
                ('nice_to_have', models.TextField(blank=True, help_text='Preferred/nice-to-have qualifications')),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('placement', 'Placement Year'), ('graduate_scheme', 'Graduate Scheme'), ('apprenticeship', 'Apprenticeship')], default='full_time', max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level (0-2 years)'), ('junior', 'Junior (1-3 years)'), ('mid', 'Mid Level (3-5 years)'), ('senior', 'Senior (5+ years)'), ('lead', 'Lead/Principal (7+ years)'), ('manager', 'Manager'), ('director', 'Director/VP')], default='entry', max_length=20)),
                ('industry', models.CharField(blank=True, help_text='Job industry/sector', max_length=100)),
                ('department', models.CharField(blank=True, help_text='Department or team', max_length=100)),
                ('location_city', models.CharField(help_text='Primary work location city', max_length=100)),
                ('location_region', models.CharField(blank=True, help_text='State/region/county', max_length=100)),
                ('location_country', models.CharField(default='United Kingdom', max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('remote_policy', models.CharField(choices=[('office', 'On-site'), ('remote', 'Fully Remote'), ('hybrid', 'Hybrid'), ('flexible', 'Flexible')], default='office', max_length=20)),
                ('remote_details', models.TextField(blank=True, help_text='Details about remote work arrangements', max_length=500)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary in GBP', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary in GBP', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('salary_currency', models.CharField(default='GBP', help_text='Salary currency code', max_length=3)),
                ('salary_period', models.CharField(choices=[('hourly', 'Per Hour'), ('daily', 'Per Day'), ('weekly', 'Per Week'), ('monthly', 'Per Month'), ('yearly', 'Per Year')], default='yearly', max_length=20)),
                ('salary_negotiable', models.BooleanField(default=False)),
                ('benefits', models.JSONField(default=list, help_text='List of benefits and perks')),
                ('visa_sponsorship', models.CharField(choices=[('available', 'Visa Sponsorship Available'), ('considered', 'Sponsorship Considered'), ('not_available', 'No Sponsorship'), ('existing_only', 'Existing Visa Holders Only')], default='available', help_text='Visa sponsorship availability', max_length=20)),
                ('sponsored_visa_types', models.JSONField(default=list, help_text='Types of visas this job can sponsor')),
                ('sponsorship_details', models.TextField(blank=True, help_text='Additional details about visa sponsorship process', max_length=1000)),
                ('minimum_visa_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary required for visa sponsorship', max_digits=10, null=True)),
                ('required_skills', models.JSONField(default=list, help_text='List of required skills')),
                ('preferred_skills', models.JSONField(default=list, help_text='List of preferred skills')),
                ('technologies', models.JSONField(default=list, help_text='Technologies and tools used')),
                ('education_level', models.CharField(blank=True, help_text='Required education level', max_length=100)),
                ('degree_subjects', models.JSONField(default=list, help_text='Relevant degree subjects')),
                ('application_deadline', models.DateTimeField(blank=True, help_text='Application deadline', null=True)),
                ('start_date', models.DateField(blank=True, help_text='Expected start date', null=True)),
                ('application_url', models.URLField(blank=True, help_text='External application URL', null=True)),
                ('application_instructions', models.TextField(blank=True, help_text='Special application instructions', max_length=1000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('filled', 'Filled'), ('expired', 'Expired'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this job prominently')),
                ('is_urgent', models.BooleanField(default=False, help_text='Mark as urgent hiring')),
                ('is_premium', models.BooleanField(default=False, help_text='Premium job posting')),
                ('view_count', models.IntegerField(default=0)),
                ('application_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this job posting expires', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Alert name/description', max_length=200)),
                ('keywords', models.CharField(blank=True, help_text='Keywords to search for', max_length=500)),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('location_region', models.CharField(blank=True, max_length=100)),
                ('job_types', models.JSONField(default=list, help_text='Job types to include in alert')),
                ('experience_levels', models.JSONField(default=list, help_text='Experience levels to include')),
                ('industries', models.JSONField(default=list, help_text='Industries to include')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary threshold', max_digits=10, null=True)),
                ('visa_sponsorship_required', models.BooleanField(default=True, help_text='Only include jobs with visa sponsorship')),
                ('is_active', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('immediate', 'Immediate')], default='daily', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Alert',
                'verbose_name_plural': 'Job Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSavedByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this job', max_length=500)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Job',
                'verbose_name_plural': 'Saved Jobs',
                'ordering': ['-saved_at'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company', 'status'], name='jobs_job_company_797da4_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_type'], name='jobs_job_job_typ_f6c220_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location_city'], name='jobs_job_locatio_c4eda0_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['experience_level'], name='jobs_job_experie_09027f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['visa_sponsorship'], name='jobs_job_visa_sp_1416c6_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['salary_min', 'salary_max'], name='jobs_job_salary__2892b4_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_at'], name='jobs_job_created_1b3a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_featured', 'status'], name='jobs_job_is_feat_5919f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobsavedbyuser',
            unique_together={('user', 'job')},
        ),
    ]
