# Generated by Django 5.2.4 on 2025-08-10 00:34

import applications.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="cover_letter_file",
            field=models.FileField(
                blank=True,
                help_text="Optional separate cover letter file",
                null=True,
                upload_to=applications.models.get_cover_letter_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="cv_file",
            field=models.FileField(
                help_text="CV/Resume file",
                upload_to=applications.models.get_cv_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="portfolio_file",
            field=models.FileField(
                blank=True,
                help_text="Optional portfolio file",
                null=True,
                upload_to=applications.models.get_portfolio_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "zip", "rar"]
                    )
                ],
            ),
        ),
    ]
