# Generated by Django 5.2.5 on 2025-08-10 19:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "algorithm_version",
                    models.CharField(default="rule_based_v1", max_length=50),
                ),
                ("total_recommendations", models.IntegerField()),
                ("average_score", models.FloatField()),
                (
                    "generation_time_ms",
                    models.IntegerField(
                        help_text="Time taken to generate recommendations in milliseconds"
                    ),
                ),
                (
                    "preferences_snapshot",
                    models.JSONField(
                        help_text="Snapshot of user preferences when batch was generated"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommendation Batch",
                "verbose_name_plural": "Recommendation Batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserJobPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_locations",
                    models.JSONField(
                        default=list, help_text="List of preferred work locations"
                    ),
                ),
                (
                    "max_commute_distance",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum commute distance in miles",
                        null=True,
                    ),
                ),
                ("open_to_remote", models.BooleanField(default=True)),
                ("open_to_hybrid", models.BooleanField(default=True)),
                (
                    "preferred_job_types",
                    models.JSONField(
                        default=list, help_text="Preferred job types/categories"
                    ),
                ),
                (
                    "preferred_industries",
                    models.JSONField(default=list, help_text="Preferred industries"),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level"),
                            ("mid", "Mid Level"),
                            ("senior", "Senior Level"),
                            ("lead", "Lead/Principal"),
                            ("executive", "Executive"),
                        ],
                        default="mid",
                        max_length=20,
                    ),
                ),
                ("min_salary", models.IntegerField(blank=True, null=True)),
                ("max_salary", models.IntegerField(blank=True, null=True)),
                ("salary_currency", models.CharField(default="GBP", max_length=3)),
                (
                    "key_skills",
                    models.JSONField(
                        default=list, help_text="List of key skills for matching"
                    ),
                ),
                (
                    "avoid_keywords",
                    models.JSONField(
                        default=list,
                        help_text="Keywords to avoid in job recommendations",
                    ),
                ),
                (
                    "preferred_company_sizes",
                    models.JSONField(default=list, help_text="Preferred company sizes"),
                ),
                (
                    "avoid_companies",
                    models.JSONField(default=list, help_text="Company IDs to avoid"),
                ),
                ("requires_sponsorship", models.BooleanField(default=True)),
                (
                    "visa_types_needed",
                    models.JSONField(
                        default=list, help_text="Types of visa sponsorship needed"
                    ),
                ),
                (
                    "notification_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("disabled", "Disabled"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                (
                    "max_recommendations",
                    models.IntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Job Preference",
                "verbose_name_plural": "User Job Preferences",
            },
        ),
        migrations.CreateModel(
            name="JobRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_score",
                    models.FloatField(help_text="Overall match score (0.0 to 1.0)"),
                ),
                ("skill_match_score", models.FloatField(default=0.0)),
                ("location_match_score", models.FloatField(default=0.0)),
                ("salary_match_score", models.FloatField(default=0.0)),
                ("company_match_score", models.FloatField(default=0.0)),
                ("experience_match_score", models.FloatField(default=0.0)),
                (
                    "match_reasons",
                    models.JSONField(
                        default=list,
                        help_text="List of reasons why this job was recommended",
                    ),
                ),
                ("viewed", models.BooleanField(default=False)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                ("clicked", models.BooleanField(default=False)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("applied", models.BooleanField(default=False)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "feedback",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("helpful", "Helpful"),
                            ("not_helpful", "Not Helpful"),
                            ("not_interested", "Not Interested"),
                            ("already_applied", "Already Applied"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("feedback_at", models.DateTimeField(blank=True, null=True)),
                ("feedback_notes", models.TextField(blank=True, max_length=500)),
                (
                    "recommendation_algorithm",
                    models.CharField(
                        default="rule_based_v1",
                        help_text="Algorithm used to generate this recommendation",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Recommendation",
                "verbose_name_plural": "Job Recommendations",
                "ordering": ["-match_score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-match_score"],
                        name="recommendat_user_id_e06583_idx",
                    ),
                    models.Index(
                        fields=["job", "-match_score"],
                        name="recommendat_job_id_0a63dc_idx",
                    ),
                    models.Index(
                        fields=["user", "viewed", "clicked"],
                        name="recommendat_user_id_1a1379_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="recommendat_created_393fdb_idx"
                    ),
                ],
                "unique_together": {("user", "job")},
            },
        ),
    ]
